import Head from "next/head";
import NextLink from "next/link";

import { Box } from "@chakra-ui/react";
import { motion } from "framer-motion";

const MotionBox = motion(Box);
const MotionLink = motion(NextLink);
export default function Home() {
  return (
    <MotionBox
      d="flex"
      justifyContent="center"
      alignItems="center"
      h="100vh"
      bgColor="#fa4e2f"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MotionBox as="main" color="#2f62fa">
        <MotionBox as="h1">Home page</MotionBox>
        <MotionLink href="/about">
          <a> Go to About </a>
        </MotionLink>
      </MotionBox>
    </MotionBox>
  );
}
